export var Participants = [
    { nom: "Aurore", genre: "Fille" },
    { nom: "Jeanne", genre: "Fille" },
    { nom: "Thomas", genre: "Garçon" },
    { nom: "Armand", genre: "Garçon" },
    { nom: "Timothé", genre: "Garçon" },
    { nom: "Yoann", genre: "Garçon" },
    { nom: "Valentin", genre: "Garçon" },
    { nom: "Pierre", genre: "Garçon" },
    { nom: "Sophie", genre: "Fille" },
    { nom: "Elise", genre: "Fille" },
    { nom: "Maxence", genre: "Garçon" },
    { nom: "Coraly", genre: "Fille" },
    { nom: "Boris", genre: "Garçon" },
    { nom: "Chaimaa", genre: "Fille" },
    { nom: "Aubrian", genre: "Garçon" },
    { nom: "Lohan", genre: "Garçon" },
    { nom: "Léo", genre: "Garçon" },
    { nom: "Rémy", genre: "Garçon" },
    { nom: "Audrey", genre: "Fille" },
    { nom: "Justine", genre: "Fille" },
    { nom: "Manon", genre: "Fille" },
    { nom: "Maëlle", genre: "Fille" },
    { nom: "Mary", genre: "Fille" },
    { nom: "Camille", genre: "Fille" }
];
